# Generated by Django 4.0.5 on 2023-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
